### ISSUE TITLE
@ApiModel.value is not being honored as an alternate type name

### ISSUE THREAD

**Issue by joegluntz** [martypitt/swagger-springmvc#382]
The swagger core annotation `ApiModel` allows you to define [an alternate name](https://github.com/wordnik/swagger-core/blob/master/modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiModel.java#L34) for the type via the `value` field. This is not being honored. The description is being applied, but the type name is only inferred from the class name.

I think the Model id and name should prefer the `@ApiModel.value` in `DefaultModelProvider`, much like we pull the model description from `@ApiModel.description`.

**Comment by andreisavu** [comment]
It would be great if this one could make it 0.9.5. Thanks!

**Comment by dilipkrish** [comment]
@handavid sorry it took so long.. but your approach seems reasonable. :+1: Given that the serialized json is a structural type and never reflects the type name in json payloads. It makes no difference whether you use ```JsonTypeName``` vs ```ApiModel``` 

Want to submit a PR?

**Comment by handavid** [comment]
sure. I'll rebase onto master first.
