### ISSUE TITLE
Problem with upgrade from 0.8.2 -> 0.9.0

### ISSUE THREAD

**Issue by indyaah** [martypitt/swagger-springmvc#497]
We were using 0.8.2 due to constraints and currently trying to upgrade to 0.8.8/0.9.0/0.9.1 unsuccessfully (partially).

Partial because we are successfully up and running with swagger but the UI wont work at all.

The problem we are facing is that after clicking on API, the dropdown/drill down list of endpoints is not showing up/listing. 

I am not sure this has more to do with the APIs JSON being generated or the Swagger-UI part.

Has anyone else faced this issue?
We are willing to investigate and put patch and PR, but need some pointers about where to start.

**Comment by indyaah** [comment]
@dilipkrish  : Closing, as created a workaround which solves the problem.

**Comment by dilipkrish** [comment]
@indyaah and the workaround was...

**Comment by indyaah** [comment]
@dilipkrish : Updated Swagger versions used by swagger-springmvc.
