### ISSUE TITLE
@ApiModelProperty "hidden" attribute has no effect

### ISSUE THREAD

**Issue by marcgise** [martypitt/swagger-springmvc#554]
I'm including this annotation in my model, and there is one attribute there that I want to hide from the API, cause it's not relevant.

As far as I know, "hidden" attribute of @ApiModelProperty does it, but it's not working. I tried defining it in the class attribute and in the getter/setter, but Swagger always includes it in the API.
```java
@ApiModel(value = "DTO description")
public class ESType {
	@ApiModelProperty(value = "The type", position = -1, required = true)
	private String type;

	@ApiModelProperty(hidden = true)
	private Class<DTO> clazz;

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@ApiModelProperty(hidden = true)
	public Class<DTO> getClazz() {
		return clazz;
	}

	@ApiModelProperty(hidden = true)
	public void setClazz(Class<DTO> clazz) {
		this.clazz = clazz;
	}
}
```

How can I hide it?

Thanks!
Marc

**Comment by dilipkrish** [comment]
@marcgise have you tried using jackson's @JsonIgnore?

**Comment by marcgise** [comment]
Yes, it works.
But I think that the purpose of this annotation is to hide the property, isn't it? Why doesn't work? :\
Using this annotation may interact with the serialization/deserialization of the objects in the application...

**Comment by knicholes** [comment]
I'm interested in this as well.  My current workaround is to put @ApiModelProperty(value="This parameter is ignored.").  It'd be nice if it excluded this value from the "Model" when read by swagger-ui.

**Comment by dilipkrish** [comment]
@marcgise It should be easy to implement but its not clear to me when you'd have a case for an "undocumented" model attribute? Do you have an example use case?

**Comment by marcgise** [comment]
Easy. Two simple cases:

1. You can have some attributes in the model used for internal purposes, but you don't want to offer it to the user.

2. As far as I know, Jackson uses getters to serialize the models, not the attributes. You can have methods that starts with "get" preffix, and Jackson also include them in your API, isn't it? We need here "hidden" property to work too.

 Personally I prefer using Gson, that use directly the attributes, but it is not what we're discussing here :)

**Comment by dilipkrish** [comment]
@marcgise 

> You can have some attributes in the model used for internal purposes, but you don't want to offer it to the user.

Thats exactly what the jackson annotations are for. To hide attributes that are not meant to be used. Why not use the attribute that controls exactly that in one fell swoop. Why not just use that?

> As far as I know, Jackson uses getters to serialize the models, not the attributes. 

[Plenty of annotations to control that](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations)

Again, my opinion, here is that using the @ApiModelProperty#hidden will not control your how serialization, so whatever the shape of the object, you'd need jackson annotations to control how a type is serialized. So I'm yet to see a good case for using this attribute.

So if you have object like this, in the case of return types
```java
class Test {
   public getName()..
   
   @ApiModeProperty(hidden= true)
   public getSuperSecret()
}
```

While you may say dont want to advertise the property, when you use the API you' see the property in clear text!!
```json
{
  "name": "test",
  "superSecret": "SECRET"
}
```

Ih the case of input parameters
```java
class Test {
   public setName(String name)..
   
   @ApiModeProperty(hidden= true)
   public setSuperSecret(String secret)
}
```

If you post with this JSON you'd get the super secret set in your model, even tho its not advertised. You do want it to be ignored in your model as well I would think. 
```json
{
  "name": "test",
  "superSecret": "SECRET"
}
```

There may be a stray case where you want your API to hide some undocumented features. That is the ONLY use case I think of. IMHO, thats bad practice in api contract design.

**Comment by marcgise** [comment]
Resuming...

1. Why Swagger offers an anotation with a property that doesn't work?

2. Why exists a property that its purpose is to hide class attributes and
it doesn't work?

3. Why am I forced to use Jacksson annotations (and forced to have this
dependency explicitly declared in my projects) when I'm not using it?

Another clear example that breaks Swagger API, is to have a model property
(not used by the final user directly, but used internally in the
application) that it's type is a Java Class.

private Class myWonderfulClass;

Try it and see how many time Swagger consumes to start, what is normal,
cause Class have multiple complex getters and setters that Jacksson
parses...

In my opinion, this "hidden" annotation property should be taken into
account.

**Comment by dilipkrish** [comment]
> Another clear example that breaks Swagger API, is to have a model property
(not used by the final user directly, but used internally in the
application) that it's type is a Java Class.

> Try it and see how many time Swagger consumes to start, what is normal,
cause Class have multiple complex getters and setters that Jacksson
parses...

@marcgise Thanks for reporting the bug, created #560 to address it

**Comment by Marza** [comment]
We would like to have the hidden attribute. For our use case we don't want to show it in the documentation since it is deprecated and should not be used but we cannot remove it yet since it is still used by some clients and therefor cannot use @JsonIgnore from Jackson.

**Comment by marcgise** [comment]
+1 for Marza

**Comment by sabithksme** [comment]
+1 for this Marza

**Comment by okohub** [comment]
+1 Marza.

**Comment by ipsi** [comment]
Would also like to see this, but for a slightly different use-case, where the API expects the same JSON object as both request and response body (e.g. it returns it for a GET and takes it for a POST to create the resource), and some of the fields are read-only - while the server won't explode if it receives those fields, they *will not* be saved or modified in any way, so I don't want to see them included in the model (preferably just for the request body model, but if I have to exclude them from both, that's OK too).

**Comment by Marza** [comment]
@ipsi For your use case it is possible to create another class and set that as the model in the api declaration. Since hiding the attribute would remove it from the response also.

**Comment by marcgise** [comment]
Please, take into account that the same attribute "hidden" is also available in @Api, @ApiOperation annotations.

Maybe it is very interesting that, at least @Api "hidden" attribute was taken into account too, cause when applied to a Controller, it means to hides the whole Controller to Swagger (and its final users, of course)

Thanks.

**Comment by fgaule** [comment]
+1

**Comment by dilipkrish** [comment]
@fgaule please create a new issue if this is not working

**Comment by madhukanth2005** [comment]
@dilipkrish
Hi,
I am using the below dependency in my spring boot app. I want to hide one of the attribute from my Model class in Swagger-UI, i am using  the below option, but still i could see this id in my swagger ui. I also tried with @ApiModelProperty(access = "hidden") in my getId() method, but its not working . Could you please guide me how to hide this attribute in my swagger-ui? Thanks in advance !!
@ApiParam(access="hide")
	private String id;

 <dependency>
			<groupId>com.mangofactory</groupId>
			<artifactId>swagger-springmvc</artifactId>
			<version>1.0.2</version>
		</dependency>

**Comment by dilipkrish** [comment]
@madhukanth2005 please move to `2.5.0` that version is not supported any longer

**Comment by madhukanth2005** [comment]
@dilipkrish 
When i use the below dependency, it says missing artifacts.

		<dependency>
			<groupId>com.mangofactory</groupId>
			<artifactId>swagger-springmvc</artifactId>
			<version>2.5.0</version>
		</dependency>

**Comment by dilipkrish** [comment]
Have you read [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)?

**Comment by madhukanth2005** [comment]
@dilipkrish 
I went through couple of docs and tried using spring fox.  the below is the code snippet i am using.
But when i hit my localhost http://localhost:8080/ReviewServices/swagger-ui.htm, i don't see my endpoints getting displayed in swagger ui.  do i need to make any other changes? Earlier i was using the swagger-springmvc version, In this case i had a static folder inside my resources folder which gain had a dist folder and this was having all the static files and index.html.
when i use hit my localhost i, e http://localhost:8080/ReviewServices/swagger-ui/index.html i use to see all my endpoints in the swagger ui. do i need to make any other changes in springfox to fix my issue? Kindly suggest. Thanks !!

<dependency>
    		<groupId>io.springfox</groupId>
    		<artifactId>springfox-swagger2</artifactId>
   			 <version>2.5.0</version>
		</dependency>
		
		<dependency>
    		<groupId>io.springfox</groupId>
   			 <artifactId>springfox-swagger-ui</artifactId>
   			 <version>2.4.0</version>
		</dependency>

@Configuration
@EnableSwagger2
public class SwaggerConfig {

	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).select()
				.apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.ant("/reviews/*")).build();
	}

**Comment by madhukanth2005** [comment]
Hi All,
I was successfully able to upgrade from mangofactory (1.0.2) version  to 2.4 version. My requirement is to hide a property from ModelAttribute class in swagger ui  and i am using below annotation but this is not working. Is there a way to hide the property to hide from Swagger - ui? Your help is highly appreciated. Thanks !!


@ApiModelProperty(hidden = true)
	private String id;

<dependency>
        <groupId>io.springfox</groupId>
         <artifactId>springfox-swagger-ui</artifactId>
         <version>2.4.0</version>
    </dependency>

**Comment by ferjanim** [comment]
Hi All,
I'm using swagger-jersey2-jaxrs 1.5.10 with jersey2 and i have a problem with models documentation (jaxrs-raml-maven-plugin 1.3.4).
It seems that sawgger only scans the primitives and ignores both Objects and ApiModelProperty annotation.
Can you please help ?
Thanks in advance

**Comment by dilipkrish** [comment]
@ferjanim You need to report this to the right project ([swagger-core](https://github.com/swagger-api/swagger-core))

**Comment by vasilhsfoto** [comment]
Hi all,

similar to what has been discussed here...

Jackson annotations clutters with Swagger ones for JsnoIgnore case. i.e
@JsonIgnore
getName() {return name}

@JsonProperty
setName() {this.name = name}

I don't want to serialize the property but I want to read it over de-serialization.
At the same time using Swagger, I want this property to be part of my API documentation.
swagger version := 1.5.10

is there any workaround for this ? I know I can use @JsonInclude rather than jsonIgnore but this doesn't solve my case

Thanks in advance

**Comment by dilipkrish** [comment]
Currently there is no good way

**Comment by vasilhsfoto** [comment]
Thanks for the reply.

I managed to create a custom JSON ignore annotation using jackson API so the property is ignored by the serialization framework while it is taken into account by swagger

**Comment by 89raghavgupta** [comment]
Hi @dilipkrish ,

I am using swagger 2.6.1.
I am using @ApiModelProperty(hidden = true) to hide the variable from JSON when using the model class as RequestBody param. What is weird is that the JSON in swagger is able to hide DateTime fields but doesn't hide any other field in the model class.

I saw that you have closed this issue, do you have any idea why it is not working?

**Comment by 89raghavgupta** [comment]
@dilipkrish   
Ok, so I guess I found the issue, the issue was I had two classes with the same name. And swagger for some reason reads one class than overrides it with info from other class. This is wired that swagger cannot distinguish between classes with the same name. So when I set @ApiModel(value = "SomeOtherName") everything worked. I think this should not happen and the swagger should identify objects based on full package name I guess.

**Comment by chenbaga** [comment]
@vasilhsfoto can you please share how you have written the custom JsonIgnore annotation. I am looking for some solution like this.

**Comment by MaksimOrlov** [comment]
@89raghavgupta here is the PR that can fix that #1671 and it is under work...

**Comment by raspacorp** [comment]
One of the comments above that suggests to create different classes for requests responses that have or not the required properties. IMHO a documentation tool shouldn't drive the design of the class hierarchy for requests or responses. It is very common and fair to reuse classes that contain a global set of properties. Developers want to be able to use for example a class 'User' that has an id, that is normally not known in the moment of the call to the 'POST /user' service as it is going to be generated in the backend, in addition to other possible properties e.g. createdDate, modifiedDate... But we want to have those in the response. It would be great if Swagger had an annotation for allowing the field to appear or not in the documentation, but it would be even more useful if we could choose if it should be documented for request or for response.

For example: ```@ApiModelProperty(responseOnly = true)```

**Comment by spekdrum** [comment]
Totally agree with raspacorp. I landed here just looking for the feature he is asking for.

**Comment by dilipkrish** [comment]
@spekdrum / @raspacorp this is a closed issue. There is already another issue to fix this.

**Comment by jous32** [comment]
What is the issue?

**Comment by dilipkrish** [comment]
Its based on #895 and on work done in PR #2056
