### ISSUE TITLE
swagger does't scan my annotation，generate APIs  failure

### ISSUE THREAD

**Issue by qq291462491** [martypitt/swagger-springmvc#570]
when I visit http://127.0.0.1:9081/api-docs ，I get
        <pre> <code> {"apiVersion":"1.0","swaggerVersion":"1.2",
"apis":[],"authorizations":[],"info":{"title":"bugkillers     back API","description":"bugkillers  API wiki ","termsOfServiceUrl":"http://127.0.0.1:9081/user/regist.do","contact":"bugkillers@163.com","license":"My License","licenseUrl":"My Apps API License URL"}}</code></pre>

why apis is null?
my code is:
<pre><code>
package org.bugkillers.back.user.controller;
import org.bugkillers.back.bean.User;
import org.bugkillers.back.user.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
@Api(value="myapi", description="Operations on Businesses", position = 1)
@Controller
@RequestMapping("/user")
public class UserController {
	@Autowired
	private UserService service;
	
	@ApiOperation(value = "regist", position = 1)
	@ResponseBody
	@RequestMapping(value = { "/regist.do" }, method = RequestMethod.GET)
	public void regist(User user){
		service.save(user);
	}
	@ApiOperation(value = "find", position = 2)
	@ResponseBody
	@RequestMapping(value = { "/find.do" }, method = RequestMethod.GET)
	public void find(){
		
		
	}
	@ApiOperation(value = "hello", position = 3)
	@ResponseBody
	@RequestMapping(value = { "/hello.do" }, method = RequestMethod.GET)
	public String hello(){
		return "Hello guys";
	}
}
</code></pre>
swagger config:
<pre><code>
package org.bugkillers.back.swagger;

import static org.ajar.swaggermvcui.SwaggerSpringMvcUi.WEB_JAR_RESOURCE_LOCATION;
import static org.ajar.swaggermvcui.SwaggerSpringMvcUi.WEB_JAR_RESOURCE_PATTERNS;
import static org.ajar.swaggermvcui.SwaggerSpringMvcUi.WEB_JAR_VIEW_RESOLVER_PREFIX;
import static org.ajar.swaggermvcui.SwaggerSpringMvcUi.WEB_JAR_VIEW_RESOLVER_SUFFIX;

import org.bugkillers.back.user.controller.UserController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.DefaultServletHandlerConfigurer;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import org.springframework.web.servlet.view.InternalResourceViewResolver;

import com.mangofactory.swagger.configuration.SpringSwaggerConfig;
import com.mangofactory.swagger.models.dto.ApiInfo;
import com.mangofactory.swagger.plugin.EnableSwagger;
import com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin;

@Configuration
@EnableWebMvc
@EnableSwagger
@ComponentScan(basePackageClasses={UserController.class},basePackages ={"org.bugkillers.back.user.controller","com.ak.swaggerspringmvc.shared.controller", "com.ak.spring3.music"})
public class CustomJavaPluginConfig extends WebMvcConfigurerAdapter {

   private SpringSwaggerConfig springSwaggerConfig;

   @Autowired
   public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
      this.springSwaggerConfig = springSwaggerConfig;
   }

   @Bean //Don't forget the @Bean annotation
   public SwaggerSpringMvcPlugin customImplementation(){
      return new SwaggerSpringMvcPlugin(this.springSwaggerConfig)
            .apiInfo(apiInfo())
            .includePatterns(".*pet.*");
   }

    private ApiInfo apiInfo() {
      ApiInfo apiInfo = new ApiInfo(
              "bugkillers back API",
              "bugkillers 后台API文档",
              "http://127.0.0.1:9081/user/regist.do",
              "bugkillers@163.com",
              "My License",
              "My Apps API License URL"
        );
      return apiInfo;
    }
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
      registry.addResourceHandler(WEB_JAR_RESOURCE_PATTERNS)
              .addResourceLocations(WEB_JAR_RESOURCE_LOCATION).setCachePeriod(0);
    }

    @Bean
    public InternalResourceViewResolver getInternalResourceViewResolver() {
      InternalResourceViewResolver resolver = new InternalResourceViewResolver();
      resolver.setPrefix(WEB_JAR_VIEW_RESOLVER_PREFIX);
      resolver.setSuffix(WEB_JAR_VIEW_RESOLVER_SUFFIX);
      return resolver;
    }

    @Override
    public void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {
      configurer.enable();
    }
   
    
}
</code></pre>

Springmvc config:

```<bean class="org.bugkillers.back.swagger.CustomJavaPluginConfig" />```

Maven:

```<dependency>
			<groupId>com.mangofactory</groupId>
			<artifactId>swagger-springmvc</artifactId>
			<version>0.9.4</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.4.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.ajar</groupId>
			<artifactId>swagger-spring-mvc-ui</artifactId>
			<version>0.4</version>
		</dependency>```

**Comment by qq291462491** [comment]
my spring version is 4.0.0.RELEASE

**Comment by qq291462491** [comment]
Is it right? Does not support spring4.x？

**Comment by dilipkrish** [comment]
@qq291462491 yes it does support 4.x. 

Seems like your include patterns are not correct
Try changing your CustomJavaPlugin to use a regex pattern than matches your controller action urls
```java
..
//TRY this for pickiing up everything
.includePatterns(".*");
//OR this for picking u all user actions
.includePatterns("/user.*"); 
```

**Comment by qq291462491** [comment]
@dilipkrish   Yeah！It worked, you are amazing！thank you.

**Comment by dilipkrish** [comment]
:+1: Closing this issue!
