### ISSUE TITLE
Please help, embedding into Spring4 throgh annotation, failed

### ISSUE THREAD

**Issue by xhe** [martypitt/swagger-springmvc#572]
I am using annotation to boot spring4 MVC project, not through xml, and this has caused difficulties when I tried to use swagger. These are three files:
1. SwaggerConfig.java
@Configuration
@EnableSwagger
@ComponentScan(basePackages = "com.spirenteng.ito.controller")
public class SwaggerConfig {

	private SpringSwaggerConfig springSwaggerConfig;
	
	
	 /**
	    * Required to autowire SpringSwaggerConfig
	    */
	   @Autowired
	   public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
	      this.springSwaggerConfig = springSwaggerConfig;
	   }

	@Bean
	public SwaggerSpringMvcPlugin customImplementation() {
		return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).apiInfo(
				apiInfo()).includePatterns(".*repo.*");
	}

	private ApiInfo apiInfo() {
		ApiInfo apiInfo = new ApiInfo("My Apps API Title",
				"My Apps API Description", "My Apps API terms of service",
				"My Apps API Contact Email", "My Apps API Licence Type",
				"My Apps API License URL");
		return apiInfo;
	}
}
2. 
public class DataJPAExampleInitializer implements WebApplicationInitializer {
   
    private static final String DISPATCHER_SERVLET_NAME = "dispatcher";
    private static final String DISPATCHER_SERVLET_MAPPING = "/";
   
    @Override
    public void onStartup(ServletContext servletContext) throws ServletException {
        AnnotationConfigWebApplicationContext rootContext = new AnnotationConfigWebApplicationContext();
        rootContext.register(ApplicationContext.class);
      
        ServletRegistration.Dynamic dispatcher = servletContext.addServlet(DISPATCHER_SERVLET_NAME, new DispatcherServlet(rootContext));
        dispatcher.setLoadOnStartup(1);
        dispatcher.addMapping(DISPATCHER_SERVLET_MAPPING);

        servletContext.addListener(new ContextLoaderListener(rootContext));
    }
}

By using this, I removed web.xml completely.

When I visit:
http://localhost:8080/ito/api-docs
the end point is not found.

Can you help to tel me how to start swagger controller and do we need to inject it into DataJPAExampleInitializer?

Thanks

**Comment by dilipkrish** [comment]
@xhe how are you pulling in your ```SwaggerConfig``` class?

**Comment by xhe** [comment]
That is crucial point here.
If I am just doing like above, defining SwaggerConfig, this class won't be pulled into Spring startup process, so I think a natual solution is embed it as a bean into ApplicationContext,
So I did like this:

@Configuration
@ComponentScan(basePackages = { "com.spirenteng.ito.controller",
		"com.spirenteng.ito.service" })
@EnableWebMvc
@ImportResource("classpath:applicationContext.xml")
@PropertySource("classpath:application.properties")
public class ApplicationContext {
@Bean
	public SwaggerConfig swaggerConfig(){
		return new SwaggerConfig();
	}
....}
If I do like this, I am having exceptions as follows:

INFO : org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
INFO : org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Wed Jan 28 21:44:18 PST 2015]; root of context hierarchy
INFO : org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Registering annotated classes: [class com.spirenteng.ito.ApplicationContext]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [applicationContext.xml]
WARN : com.jolbox.bonecp.BoneCPConfig - Max Connections < 1. Setting to 20
INFO : org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Mapped "{[/],methods=[GET],params=[],headers=[],consumes=[],produces=[],custom=[]}" onto public java.lang.String com.spirenteng.ito.controller.HomeController.showPage()
INFO : org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Mapped "{[/repositories/],methods=[GET],params=[],headers=[],consumes=[],produces=[],custom=[]}" onto public java.util.List<com.spirenteng.ito.model.Repository> com.spirenteng.ito.controller.RepositoryController.getAllRepositories()
INFO : org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter - Looking for @ControllerAdvice: Root WebApplicationContext: startup date [Wed Jan 28 21:44:18 PST 2015]; root of context hierarchy
WARN : org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'swaggerConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void com.spirenteng.ito.SwaggerConfig.setSpringSwaggerConfig(com.mangofactory.swagger.configuration.SpringSwaggerConfig); nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.mangofactory.swagger.configuration.SpringSwaggerConfig] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)

So how can I inject swagConfig into spring through annotation?

**Comment by xhe** [comment]
even if I removed @Configuration from swaggerConfig, still same error, something wrong?

**Comment by xhe** [comment]
Hi Dilip,
Can you help to figure out how to use java annotation to embed swagger? I
am not using spring boot, just WebApplicationInitializer
Thanks
Frank

**Comment by adrianbk** [comment]
@xhe have you managed to get things working?

**Comment by xhe** [comment]
Using spring boot is my solution. If you start a new project, there is
really no reason not using spring boot.
