### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by robert-morschel** [martypitt/swagger-springmvc#574]
Hi,

I downloaded the branch zip and am trying to build locally.  All is well except the tests fail (see below).

Any suggestions?  (Note: because of company firewall restrictions I had to build against a slightly different version of mockito)

Regards,
Robert

swagger-contract-tests:build
swagger-models:assemble
swagger-models:checkstyleMain
swagger-models:compileTestJava
arning: [options] bootstrap class path not set in conjunction with -source 1.6
 warning
swagger-models:compileTestGroovy
arning: [options] bootstrap class path not set in conjunction with -source 1.6
 warning
swagger-models:processTestResources
swagger-models:testClasses
swagger-models:checkstyleTest
swagger-models:findbugsMain
swagger-models:test

om.mangofactory.swagger.models.dto.ApiDescriptionSpec > should serialize FAILED
   org.spockframework.runtime.SpockComparisonFailure at ApiDescriptionSpec.groovy:15

om.mangofactory.swagger.models.dto.ApiInfoSpec > should serialize FAILED
   org.spockframework.runtime.SpockComparisonFailure at ApiInfoSpec.groovy:18

om.mangofactory.swagger.models.dto.ApiKeySpec > should produce a header key FAILED
   org.spockframework.runtime.SpockComparisonFailure at ApiKeySpec.groovy:10

om.mangofactory.swagger.models.dto.ApiKeySpec > should produce a custom key FAILED
   org.spockframework.runtime.SpockComparisonFailure at ApiKeySpec.groovy:20

**Comment by adrianbk** [comment]
The version of mockito should be as specified via gradle dependencies.
