### ISSUE TITLE
Swagger upgrade from 0.6.6 to 0.8.8 version

### ISSUE THREAD

**Issue by Sumit-S** [martypitt/swagger-springmvc#575]
We upgraded Swagger from 0.6.6 to 0.8.8.. We changed annotation like @ApiError to @ApiResponse and added @EnableSwagger, @Configuration. We also did necessary changes so that 'Default' word won't come in basepath. but still it is not working. Are there any other changes needs to be done to make swagger work as compared to version 0.6.6 version. 
We are using Spring 3.2.4 version. 

Thanks in advance !

**Comment by dilipkrish** [comment]
Please try and upgrade to 0.9.4. Since there is a significant difference between 0.6.x and 0.9.x. I'd advise you to configure the application per the instructions in the readme as if it were a new application. There is not migration path between those versions. 

Let me know if u run into issues

**Comment by Sumit-S** [comment]
Thanks dilipkrish !
I am new to Swagger as well as GitHub. Can you please tell me where can I get those instructions readme file ?

**Comment by joshita14** [comment]
Hi, 

I am new to swagger.
I am using 0.9.5 swagger, and is working on integrating it with Spring mvc.

Followed the instructions on Swagger-springmvc and is using SwaggerSpringMvcPlugin Spring Java Configuration .
Downloaded the UI added the contents from the "dist".

I have the following problems 
I am deploying the webapp to tomcat and is accessing the swagger UI

I am able to access the index.html with the discoveryURL "http://localhost:8080/rest-2.0/api-docs.json" but it does not show the API it generated for my application
Unable to read api 'location-controller' from path http://localhost:8080/rest-2.0/api-docs.json/default/location-controller (server returned undefined)

I am able to view the generated JSON on this URL http://localhost:8080/rest-2.0/api-docs/default/location-controller.json

Please help me , i have demo in few hrs from now.

Thanks

**Comment by Sumit-S** [comment]
Hi @dilipkrish ,

I upgraded swagger version to 0.9.4 and I am receiving json response but my html is not working. It is giving same error (server returned undefined).

To be specific when I tried to put @Api(basePath = "abc/xyz", description = "Operations pertaining to documents", value = "abc/xyz"). It is showing the path as 
<path> api-docs/abcxyz/</path>. 

Can you please tell why it is ignoring the forward slash '/' symbol. So even though I am receiving raw  data my UI is not working. 

Before this I had swagger 0.6.6 completely working but after I updates jQuery it was giving error like 

This page contains the following errors:
error on line 1 at column 3818: StartTag: invalid element name
Below is a rendering of the page up to the first error.

So we decided to upgrade swagger version. Please help us with this issue.

 Thanks in advance !

**Comment by dilipkrish** [comment]
@Sumit-S the basePath is ignored, so that definitely will not work. Not really sure what the error you're seeing is, is that a javascript error? If so try upgrading to the [latest swagger-ui].(https://github.com/swagger-api/swagger-ui).

**Comment by adrianbk** [comment]
Assuming resolved.
