### ISSUE TITLE
Unable to view the generated API doc from swagger UI, using 0.9.5

### ISSUE THREAD

**Issue by joshita14** [martypitt/swagger-springmvc#576]
Hi,

I am new to swagger.
I am using 0.9.5 swagger, and is working on integrating it with Spring mvc.

Followed the instructions on Swagger-springmvc and is using SwaggerSpringMvcPlugin Spring Java Configuration .
Downloaded the UI added the contents from the "dist".

I have the following problems 
I am deploying the webapp to tomcat and is accessing the swagger UI

I am able to access the index.html with the discoveryURL "http://localhost:8080/rest-2.0/api-docs.json" but it does not show the API it generated for my application
Unable to read api 'location-controller' from path http://localhost:8080/rest-2.0/api-docs.json/default/location-controller (server returned undefined)

I am able to view the generated JSON on this URL http://localhost:8080/rest-2.0/api-docs/default/location-controller.json

Please help me , i have demo in few hrs from now.

Thanks

**Comment by dilipkrish** [comment]
Try removing the **.json** extension altogether.

**Comment by dilipkrish** [comment]
@joshita14 Can we use this issue to communicate all queries related to your problem

**Comment by joshita14** [comment]
Yes, sure.

Thanks

**Comment by joshita14** [comment]
Hi ,

This is my configuration


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

import com.mangofactory.swagger.configuration.SpringSwaggerConfig;
import com.mangofactory.swagger.models.dto.ApiInfo;
import com.mangofactory.swagger.plugin.EnableSwagger;
import com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin;

@Configuration
@EnableWebMvc
@EnableSwagger
@ComponentScan("com.mypackage")
public class CustomJavaPluginConfig {

	private SpringSwaggerConfig springSwaggerConfig;

	@Autowired
	public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
		this.springSwaggerConfig = springSwaggerConfig;
	}

	@Bean
	// Don't forget the @Bean annotation
	public SwaggerSpringMvcPlugin customImplementation() {
		return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).apiInfo(
				apiInfo()).includePatterns(".*api.*");
	}

	private ApiInfo apiInfo() {
		ApiInfo apiInfo = new ApiInfo("application",
				, "My Apps API terms of service",
				"My Apps API Contact Email", "My Apps API Licence Type",
				"My Apps API License URL");
		return apiInfo;
	}
}

**Comment by joshita14** [comment]
My Web.xml
<welcome-file-list>

		<welcome-file>index</welcome-file>

	</welcome-file-list>

**Comment by joshita14** [comment]
Index.html
<script type="text/javascript">
    $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = "http://localhost:8080/rest-2.0/api-docs";
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            /*
            initOAuth({
              clientId: "your-client-id",
              realm: "your-realms",
              appName: "your-app-name"
            });
            */
          }
          $('pre code').each(function(i, e) {
            hljs.highlightBlock(e)
          });
        },

**Comment by joshita14** [comment]
When i try to access 
http://localhost:8080/rest-2.0/api-docs it throws error "cant read from http://localhost:8080/rest-2.0/api-docs", when i manually change api-docs to api-docs.json its throws up the error

Unable to read api 'location-controller' from path http://localhost:8080/rest-2.0/api-docs.json/default/location-controller (server returned undefined)

**Comment by joshita14** [comment]
Both the generated JSONs are accessible via
http://localhost:8080/rest-2.0/api-docs.json

and http://localhost:8080/rest-2.0/api-docs/default/location-controller.json
When  i directly hit these.

**Comment by dilipkrish** [comment]
Looks like you aren't formatting code correctly. Seems like its getting lost. Could you repost your snippets with the correct markdown formatting? See [here for help](https://guides.github.com/features/mastering-markdown/) and look for code. 

May be easier if you can you share your repo?

**Comment by joshita14** [comment]
Okay, which files you want to look again ? Please can you let me know, i will repost.

**Comment by joshita14** [comment]
I have made the following changes 

1. Added the CustomJavaPluginConfig file mentioned here 
     https://github.com/martypitt/swagger-springmvc

2. In The pom.xml i have the following entry 
  	      <dependency>
		    <groupId>com.mangofactory</groupId>
		    <artifactId>swagger-springmvc</artifactId>
		    <version>0.9.5</version>
		</dependency>

 and 
              <repository>
		    <id>oss-jfrog-artifactory</id>
		    <name>oss-jfrog-artifactory-releases</name>
		    <url>http://oss.jfrog.org/artifactory/oss-release-local</url>
		</repository>


3. I have index.html as the only entry in web.xml

4. Downloaded the UI and modified the index.html with the 
discovery URL as "http://localhost:8080/rest-2.0/api-docs.json"

5. Deployed the webapp in tomcat and accessing the Swagger UI , with all the errors mentioned above.

**Comment by joshita14** [comment]
Hi,

I have the repo here 

[GitHub](http://github.com)

**Comment by joshita14** [comment]
![capture](https://cloud.githubusercontent.com/assets/10032130/6086088/18bbe600-ae65-11e4-8703-84a4ea0b8acc.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10032130/6086089/18bd30be-ae65-11e4-92fb-7c79c597c348.PNG)

**Comment by joshita14** [comment]
My UI is working now, I am able to view the documentation.

I have one more doubt, the API VERSION :1.0 is not visible in UI, it was visible before

Thanks

Regards

**Comment by dilipkrish** [comment]
:+1:

I can see it in the screenshot you provided :confused:

**Comment by joshita14** [comment]
:) Its the old snapshot , the new one  after all the problems solved does not show.
