### ISSUE TITLE
Is there anyway to remove swaggerGroups?

### ISSUE THREAD

**Issue by bsafa** [martypitt/swagger-springmvc#583]
I am trying to import my generated swagger into a tool that accepts swagger however it does not know how to deal with swagger groups. I am wondering if there is anyway to remove or disable swagger groups so it does not add 'default' .

The tool in case you are curious is WSO2 api manager publisher

Thanks.

Looking forward to a response.

**Comment by dilipkrish** [comment]
@bsafa It is conformant to the spec, and swagger-ui / swagger.js is able to load it without problems. So its most certainly a problem with WSO2's tooling. Obviously I see that there may be use case for not rendering the group if there is only one group. Would you like to try and submit a patch?

**Comment by bsafa** [comment]
@dilipkrish Thanks for your response. That is what I figured after reviewing 2.0. I am going to try but I am not sure if it is worth the investment like you said. I will see if I can get anywhere with it if not then I would wait for migration to 2.0 spec. Thanks again.
