### ISSUE TITLE
How to enable pretty print JSON for swagger 0.9.5 , springmvc 

### ISSUE THREAD

**Issue by joshita14** [martypitt/swagger-springmvc#584]
Hi,

I have to enable pretty-print JSON , I am using CustomJavaPluginConfig for generating the API-DOCS.

Please suggest how can i do that.

Thanks

Regards

**Comment by dilipkrish** [comment]
You'd need to use jacksons object mapper for that. See this [stackoverflow answer for an example](http://stackoverflow.com/questions/14515994/convert-json-string-to-pretty-print-json-output-using-jackson)

**Comment by hestad** [comment]
I don't think the original poster got this working by using that stackoverflow answer. I have tried the same by setting objectMapper.enable(SerializationFeature.INDENT_OUTPUT); with no effect. One solution is to extend ObjectMapper with a CustomObjectMapper and override registerModule(). Then you can check for the "SwaggerJacksonModule" and then creating this module yourself by copying the code in SwaggerJacksonProvider. This is super-dirty, but it works :)
