### ISSUE TITLE
Hiding internal parameters

### ISSUE THREAD

**Issue by amirabiri** [martypitt/swagger-springmvc#585]
I've tried to look but couldn't find a solution to this:

    @RequestMapping("/api/something")
    @ApiOperation("Get something")
    public Response getSomething(@CustomResolved Foo foo) {
        ...
    }

In the above example, `swagger-springmvc` will generate a parameter entry for `foo`, but `foo` isn't really an API param - it's an internal param provided by a custom resolver. It is essentially equivalent to HttpServletRequest etc.

I can't find a way to tell `swagger-springmvc` to ignore this parameter. I noticed that in wordnik `@ApiParam` contains [`access`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiParam.java#L85) for this purpose - but I can't find actual support for this or the equivalent of wordnik's filters.

It appears this functionality is missing.

**Comment by dilipkrish** [comment]
@amirabiri  Its not possible for a library to understand the internals of "your" api. I suspect that you want to do one of the two below

- Want to ignore the Foo parameter altogether. i.e. if you arent using Foo in any other action or context then you could do [like this](https://github.com/martypitt/swagger-springmvc#excluding-spring-handler-method-arguments-or-custom-types)
- If thats not the case, or if you want to substitute the representation of ```Foo``` with some other type, then you could use the model substitution via [genericModelSubstitutes](https://github.com/martypitt/swagger-springmvc/blob/master/swagger-springmvc/src/main/java/com/mangofactory/swagger/plugin/SwaggerSpringMvcPlugin.java#L285) and/or [directModelSubstitute](https://github.com/martypitt/swagger-springmvc/blob/master/swagger-springmvc/src/main/java/com/mangofactory/swagger/plugin/SwaggerSpringMvcPlugin.java#L270)

Hope those are useful pointers

**Comment by adrianbk** [comment]
Assuming this is resolved

**Comment by amirabiri** [comment]
Sorry took me a while to respond.

What I'm referring too already exists in Swagger (see [here](https://github.com/swagger-api/swagger-core/blob/e9d084498a26f55ca018d534fa1f5ad30dc14f67/samples/java-play2/app/security/AuthorisationFilter.java#L31) and [here](https://github.com/swagger-api/swagger-core/blob/a770366706d0989bfb9e805733a406377c8e49a4/modules/swagger-core/src/main/scala/com/wordnik/swagger/model/SwaggerModels.scala#L115) and this [SO question](http://stackoverflow.com/questions/22812365/how-to-hide-a-parameter-in-swagger)).

The problem is specific to swagger-springmvc, as it doesn't output the `paramAccess` property, and I also wasn't able to find how to register a filter.

Obviously I wouldn't expect a library to understand the internals of "my" api. I would however expect a simple ability to flag something to be ignored by a library - which swagger supports.

**Comment by adrianbk** [comment]
@amirabiri did you try the following: 

```
swaggerSpringMvcPlugin.ignoredParameterTypes(CustomResolved.class)
```

**Comment by amirabiri** [comment]
I gave a pseudo example. The real-world case isn't discriminated by the type of the parameter. For example a `User` object in some endpoints is a real param (add, update) and in others it is a custom resolve (Current logged in user, etc). In other cases We use custom resolving on a param of type `Long`, and obviously we can't blanket ignore all `Long` params...

**Comment by adrianbk** [comment]
I see.. Unfortunately, it's unlikely we will support this with swagger1.2 - we are working towards supporting swagger 2.0.
