### ISSUE TITLE
swagger   Caused By: java.lang.VerifyError: Cannot inherit from final class

### ISSUE THREAD

**Issue by azizkhani** [martypitt/swagger-springmvc#591]
in spring 4 i get this exception in weblogic

**Comment by dilipkrish** [comment]
Please see [these guidelines](https://github.com/martypitt/swagger-springmvc/wiki/Issue-Submission). With such little information there is absolutely no way for anyone to help you!

**Comment by mallim** [comment]
have you upgrade the guava dependency to the latest version?

**Comment by adrianbk** [comment]
Assuming resolved due to lack of response.

**Comment by BigSocial** [comment]
I had this same issue on Weblogic 12c using Swagger 1.5.1 M2 which pulls in Guava 15. Adding a dependency for Guava 18 in my POM (thereby overriding Guava 15) resolved the issue. Thanks for the lead.

**Comment by aiionx** [comment]
(y) thanks BigSocial
