### ISSUE TITLE
swagger-springmvc generates ApiResponses that are not defined in @ApiResponses

### ISSUE THREAD

**Issue by heapifyman** [martypitt/swagger-springmvc#609]
Using the following annotation
```java
@ApiResponses(value = {
    @ApiResponse(code = 200, message = "Success", response = MyModel.class),
    @ApiResponse(code = 500, message = "Internal Server Error", response = MyErrorModel.class)
})
```

I would expect that only those two responses show up in the generated swagger ui.

But I always also get default entries for at least 401, 403 and 404 in the generated list of Response Messages. For POST operations I also get 201.

Is this a bug or some missing configuration? How do I get rid of the superfluous Response Messages?

**Comment by dilipkrish** [comment]
You need to use the [useDefaultResponseMessages](https://github.com/martypitt/swagger-springmvc/blob/master/swagger-springmvc/src/main/java/com/mangofactory/swagger/plugin/SwaggerSpringMvcPlugin.java#L298) to false so that the default response codes are not applied.

**Comment by heapifyman** [comment]
Ok. Thanks, @dilipkrish
